// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yquttchxjkhclipqhbze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxdXR0Y2h4amtoY2xpcHFoYnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQxMjIsImV4cCI6MjA3MzEwMDEyMn0.9g31jMviF8yQZ8Mur4MGlP8vmLrpb8chKNMzxUx2pqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});